export async function GET(request: Request) {

  await new Promise((resolve) => setTimeout(resolve, 2000));

  const temas = [
    { temas_id: 1, temas_nome: "Doença exemplo 1", temas_nome_area: "Pneumologia" },
    { temas_id: 2, temas_nome: "Doença exemplo 2", temas_nome_area: "Cardiologia" },
    { temas_id: 3, temas_nome: "Doença exemplo 3", temas_nome_area: "Neurologia" },
    { temas_id: 4, temas_nome: "Doença exemplo 4", temas_nome_area: "Infectologia" },
    { temas_id: 5, temas_nome: "Doença exemplo 5", temas_nome_area: "Endocrinologia" },
    { temas_id: 6, temas_nome: "Doença exemplo 6", temas_nome_area: "Reumatologia" },
    { temas_id: 7, temas_nome: "Doença exemplo 7", temas_nome_area: "Gastroenterologia" },
    { temas_id: 8, temas_nome: "Doença exemplo 8", temas_nome_area: "Psiquiatria" },
    { temas_id: 9, temas_nome: "Doença exemplo 9", temas_nome_area: "Dermatologia" },
    { temas_id: 10, temas_nome: "Doença exemplo 10", temas_nome_area: "Oncologia" },
    { temas_id: 11, temas_nome: "Doença exemplo 11", temas_nome_area: "Ortopedia" },
    { temas_id: 12, temas_nome: "Doença exemplo 12", temas_nome_area: "Oftalmologia" },
    { temas_id: 13, temas_nome: "Doença exemplo 13", temas_nome_area: "Otorrinolaringologia" },
    { temas_id: 14, temas_nome: "Doença exemplo 14", temas_nome_area: "Urologia" },
    { temas_id: 15, temas_nome: "Doença exemplo 15", temas_nome_area: "Ginecologia" },
    { temas_id: 16, temas_nome: "Doença exemplo 16", temas_nome_area: "Obstetrícia" },
    { temas_id: 17, temas_nome: "Doença exemplo 17", temas_nome_area: "Hematologia" },
    { temas_id: 18, temas_nome: "Doença exemplo 18", temas_nome_area: "Imunologia" },
    { temas_id: 19, temas_nome: "Doença exemplo 19", temas_nome_area: "Nefrologia" },
    { temas_id: 20, temas_nome: "Doença exemplo 20", temas_nome_area: "Pediatria" },
    { temas_id: 21, temas_nome: "Doença exemplo 21", temas_nome_area: "Pneumologia" },
    { temas_id: 22, temas_nome: "Doença exemplo 22", temas_nome_area: "Cardiologia" },
    { temas_id: 23, temas_nome: "Doença exemplo 23", temas_nome_area: "Neurologia" },
    { temas_id: 24, temas_nome: "Doença exemplo 24", temas_nome_area: "Infectologia" },
    { temas_id: 25, temas_nome: "Doença exemplo 25", temas_nome_area: "Endocrinologia" },
    { temas_id: 26, temas_nome: "Doença exemplo 26", temas_nome_area: "Reumatologia" },
    { temas_id: 27, temas_nome: "Doença exemplo 27", temas_nome_area: "Gastroenterologia" },
    { temas_id: 28, temas_nome: "Doença exemplo 28", temas_nome_area: "Psiquiatria" },
    { temas_id: 29, temas_nome: "Doença exemplo 29", temas_nome_area: "Dermatologia" },
    { temas_id: 30, temas_nome: "Doença exemplo 30", temas_nome_area: "Oncologia" },
    { temas_id: 31, temas_nome: "Doença exemplo 31", temas_nome_area: "Ortopedia" },
    { temas_id: 32, temas_nome: "Doença exemplo 32", temas_nome_area: "Oftalmologia" },
    { temas_id: 33, temas_nome: "Doença exemplo 33", temas_nome_area: "Otorrinolaringologia" },
    { temas_id: 34, temas_nome: "Doença exemplo 34", temas_nome_area: "Urologia" },
    { temas_id: 35, temas_nome: "Doença exemplo 35", temas_nome_area: "Ginecologia" },
    { temas_id: 36, temas_nome: "Doença exemplo 36", temas_nome_area: "Obstetrícia" },
    { temas_id: 37, temas_nome: "Doença exemplo 37", temas_nome_area: "Hematologia" },
    { temas_id: 38, temas_nome: "Doença exemplo 38", temas_nome_area: "Imunologia" },
    { temas_id: 39, temas_nome: "Doença exemplo 39", temas_nome_area: "Nefrologia" },
    { temas_id: 40, temas_nome: "Doença exemplo 40", temas_nome_area: "Pediatria" },
    { temas_id: 41, temas_nome: "Doença exemplo 41", temas_nome_area: "Pneumologia" },
    { temas_id: 42, temas_nome: "Doença exemplo 42", temas_nome_area: "Cardiologia" },
    { temas_id: 43, temas_nome: "Doença exemplo 43", temas_nome_area: "Neurologia" },
    { temas_id: 44, temas_nome: "Doença exemplo 44", temas_nome_area: "Infectologia" },
    { temas_id: 45, temas_nome: "Doença exemplo 45", temas_nome_area: "Endocrinologia" },
    { temas_id: 46, temas_nome: "Doença exemplo 46", temas_nome_area: "Reumatologia" },
    { temas_id: 47, temas_nome: "Doença exemplo 47", temas_nome_area: "Gastroenterologia" },
    { temas_id: 48, temas_nome: "Doença exemplo 48", temas_nome_area: "Psiquiatria" },
    { temas_id: 49, temas_nome: "Doença exemplo 49", temas_nome_area: "Dermatologia" },
    { temas_id: 50, temas_nome: "Doença exemplo 50", temas_nome_area: "Oncologia" },
  ];

  return new Response(JSON.stringify(temas), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}
