import "@/app/globals.css";
import type { Metadata } from "next";
import { comfortaa, sfProDisplay, sfProText, inter } from "./fonts";
import styles from "./layout.module.css";
import SplashScreenProvider from "./providers/SplashScreenProvider";
import { cookies } from "next/headers";
import SplashScreen from "./components/splashScreen/SplashScreen";

export const metadata: Metadata = {
  title: "root layout",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const splashShown = cookieStore.get("splash_shown")?.value;

  return (
    <html
      lang="en"
      className={`${comfortaa.variable} ${sfProDisplay.variable} ${sfProText.variable} ${inter.variable}`}
    >
      <body className={styles.screen}>{!splashShown ? <SplashScreen /> : children}</body>
    </html>
  );
}
