import type { Metadata } from "next";
import "./globals.css";
import { comfortaa, sfProDisplay, sfProText } from "./fonts";
import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${comfortaa.variable} ${sfProDisplay.variable} ${sfProText.variable}`}>
      <body className={`antialiased screen`}>
        <Header />
        <main className="grow p-5 mt-[82px] mb-[70px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
